### ISSUE TITLE
Docker not working

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/india-forecast-app#25]
## Detailed Description
App is working when running with python, but not in docker env

I used docker compse
```
version: "3"

services:
  forecast:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_URL=postgresql://main:password@host.docker.internal:5433/indiadbdevelopment
      - NWP_ZARR_PATH=./nwp.zarr
    expose:
      - 5433
    ports:
      - 5433:5433
    extra_hosts:
      # To get DOCKERHOST use
      # export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)
      - "dockerhost:${DOCKERHOST}"
    volumes:
      - ./india_forecast_app/:/app/india_forecast_app
```

## Context
trying to get windnet running for the first time

Docker file hangs (but doesnt fail)

![Screenshot 2024-02-27 at 18 08 12](https://github.com/openclimatefix/india-forecast-app/assets/34686298/bc036de3-e2cc-4043-8fc9-7a9d4b1146cf)

## Possible Implementation
- not sure
